using System.Collections.Generic;

namespace Pluralsight.Learner.WPF;

public class Iso6391Languages
{
	public static readonly SortedDictionary<string, string> Codes = new SortedDictionary<string, string>
	{
		{ "Afrikaans", "af" },
		{ "Amharic", "am" },
		{ "العربية", "ar" },
		{ "Azerbaijani", "az" },
		{ "Belarusian", "be" },
		{ "Български", "bg" },
		{ "ব\u09beঙ\u09cdগ\u09beল\u09bf", "bn" },
		{ "Bosanski", "bs" },
		{ "Català", "ca" },
		{ "Cebuano", "ceb" },
		{ "Corsican", "co" },
		{ "Čeština", "cs" },
		{ "Cymreig", "cy" },
		{ "dansk", "da" },
		{ "Deutsch", "de" },
		{ "Ελληνικά", "el" },
		{ "English", "en" },
		{ "Esperanto", "eo" },
		{ "Español", "es" },
		{ "Eesti", "et" },
		{ "Basque", "eu" },
		{ "فارسی", "fa" },
		{ "suomi", "fi" },
		{ "Français", "fr" },
		{ "Western Frisian", "fy" },
		{ "Gaeilge", "ga" },
		{ "Gaelic", "gd" },
		{ "Galician", "gl" },
		{ "ગ\u0ac1જર\u0abeત\u0ac0", "gu" },
		{ "Hausa", "ha" },
		{ "Hawaiian", "haw" },
		{ "עברית", "he" },
		{ "ह\u093f\u0902द\u0940", "hi" },
		{ "Hmong", "hmn" },
		{ "Hrvatski", "hr" },
		{ "Ayisyen", "ht" },
		{ "magyar", "hu" },
		{ "Armenian", "hy" },
		{ "Indonesia", "id" },
		{ "Igbo", "ig" },
		{ "Íslenska", "is" },
		{ "Italiano", "it" },
		{ "日本語", "ja" },
		{ "Georgian", "ka" },
		{ "Қазақша", "kk" },
		{ "Central Khmer", "km" },
		{ "ಕನ\u0ccdನಡ", "kn" },
		{ "한국어", "ko" },
		{ "کوردی", "ku" },
		{ "Kirghiz", "ky" },
		{ "Latin", "la" },
		{ "Luxembourgish", "lb" },
		{ "Lao", "lo" },
		{ "Lietuvių", "lt" },
		{ "Latviešu", "lv" },
		{ "Malagasy", "mg" },
		{ "Māori", "mi" },
		{ "Macedonian", "mk" },
		{ "മലയ\u0d3eള\u0d02", "ml" },
		{ "Mongolian", "mn" },
		{ "मर\u093eठ\u0940", "mr" },
		{ "Melayu", "ms" },
		{ "Malti", "mt" },
		{ "Burmese", "my" },
		{ "Nepali", "ne" },
		{ "Nederlands", "nl" },
		{ "Norsk", "no" },
		{ "Chichewa", "ny" },
		{ "ਪ\u0a70ਜ\u0a3eਬ\u0a40", "pa" },
		{ "Polski", "pl" },
		{ "د فشار", "ps" },
		{ "Português", "pt" },
		{ "Română", "ro" },
		{ "русский", "ru" },
		{ "Sindhi", "sd" },
		{ "Sinhala", "si" },
		{ "slovenčina", "sk" },
		{ "slovenščina", "sl" },
		{ "Samoa", "sm" },
		{ "Shona", "sn" },
		{ "Somali", "so" },
		{ "Albanian", "sq" },
		{ "Srpski", "sr" },
		{ "Sotho", "st" },
		{ "Sundanese", "su" },
		{ "Svenska", "sv" },
		{ "Kiswahili", "sw" },
		{ "தம\u0bbfழ\u0bcd", "ta" },
		{ "త\u0c46ల\u0c41గ\u0c41", "te" },
		{ "Tajik", "tg" },
		{ "ไทย", "th" },
		{ "Tagalog", "tl" },
		{ "Türkçe", "tr" },
		{ "українська", "uk" },
		{ "اردو", "ur" },
		{ "Uzbek", "uz" },
		{ "Việt", "vi" },
		{ "Xhosa", "xh" },
		{ "Yiddish", "yi" },
		{ "Yoruba", "yo" },
		{ "中文", "zh" },
		{ "Zulu", "zu" }
	};
}
